server:
  port: 8001
  servlet:
    context-path: /api
  error:
    include-message: always
spring:
  application:
    name: customer-microservice
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true